name: Pull Request Validation and Labeling
run-name: ${{ github.actor }} has opened or updated an Pull Request 🚀
on:
  pull_request: # by default, when a pr is opened or synchronized

permissions:
  contents: read

jobs:
  # Let us add a label to the PR based on the branch name and files changed
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v5

  linting:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.2.1
        env:
          # This is a token that is automatcially genereated by GitHub Actions and lasts until the job is complete
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_KUBERNETES_KUBECONFORM: ${{ inputs.enable_kubeconform }}
          VALIDATE_NATURAL_LANGUAGE: ${{ inputs.enable_natural_language }}
